apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vdfj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vdfj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vdfj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vdfj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vdfj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-inbl-tenant/rhtap-demo-app/hacbs-test-project-vdfj@sha256:4ee6574e075fd17a485b8c6960c7796d704864f518e6258b73fcf42b59070a9f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
