apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vdfj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-inbl-tenant/rhtap-demo-app/hacbs-test-project-vdfj@sha256:4ee6574e075fd17a485b8c6960c7796d704864f518e6258b73fcf42b59070a9f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
